[[intro]]
== You Know, for Search... - 검색을 아시나요...

Elasticsearch는
https://lucene.apache.org/core/[Apache Lucene(TM)]을 기반으로 만들어진 Open Source 검색 엔진이며,
full text 검색 엔진 라이브러리다. Lucene은 Open Source와 상업용 양쪽 모두를
살펴보더라도 오늘날 현존하는 가장 고급스러고, 고성능의, 완벽한 기능을 갖춘 검색 엔진 라이브러리다.

그러나, Lucene은 단지 라이브러리일 뿐이다. 그것의 활용을 최대한하려면, Java로 작업을 해야 하고
Lucene을 응용프로그램에 직접 통합해야 한다. 더 심각한 것은 Lucene이 어떻게 동작하는지
이해하기 위해서는, 정보 검색의 정도를 알 필요가 있을지도 모른다. 그만큼 Lucene은 _매우_ 복잡하다.

Elasticsearch는 모든 색인과 검색을 위해, Java((("Java")))로 작성하고 내부적으로 Lucene을 사용한다.
하지만 그것은 간단하고 일관된 RESTful API 뒤에 Lucene의 복잡함을 숨겨, full text 검색을 쉽게 하는 것을 목표로 하고 있다.

그러나, Elasticsearch는 Lucene 보다 낫고, ``단순한'' full text 검색 이상이다. ((("Elasticsearch", "capabilities"))) 아래처럼…

* _모든 field_가 색인하고 검색할 수 있는 실시간 분산 document 저장소
* 실시간 분석이 가능한 분산 검색 엔진
* 수백 개의 서버와 수 PB(PetaByte)의 구조적/비구조적 데이터로 확장 가능

그리고, Elasticsearch는 모든 기능을 단일 서버에 packaging 했다. 그래서 응용프로그램이
간단한 RESTful API나 당신이 선호하는 프로그래밍 언어 기반의 Web 클라이언트를 사용하거나
심지어 Command line을 통해 이야기할 수 있다.

Elasticsearch를 시작하는 것은 쉽다. 실용적인 기본 설정을 제공하고, 초보자에게는 복잡한
검색 이론을 숨긴다. 설치 후 _바로 사용_할 수 있다. 최소한의 이해를 바탕으로, 바로 제품화할 수 있다.
((("Elasticsearch", "installing")))

Elasticsearch는 무료로 내려 받고((("Apache 2 license"))), 사용하고, 변경할 수 있다.
Elasticsearch는 http://www.apache.org/licenses/LICENSE-2.0.html[Apache 2 license]에서
이용 가능하고, 가장 유연하게 사용 가능한 open source license 중 하나이다.

Elasticsearch에 대한 지식이 늘어날수록, Elasticsearch의 고급 기능을 더 많이 활용할 수 있다.
전체 엔진은 설정 가능하도록 되어 있고, 매우 유연하다. Elasticsearch를 사용하려는 분야에 맞도록 설정하기 위해,
Elasticsearch의 고급 기능을 골라 선택하자.

.시간의 뒤안길 …
***************************************

몇 년 전에, 갓 결혼한 무직의 개발자 Shay Banon는 셰프가 되기위해 공부하러 가는 아내를
따라 런던으로 갔다. 돈벌이가 되는 직장을 구하는 동안, 그는 Lucene의 초기 버전을 만지작
거리기 시작했고, 그의 아내의 조리법 검색 엔진 구축을 대한 관심을 가졌다.

요리사가 되려고 공부를 하고 있는 그의 아내를 따라 런던으로 갔다. 직장을 구하는 동안,
아내의 조리법을 검색하는 엔진을 구축하려고, Lucene의 초기 버전을 만들기 시작하였다.
Lucene으로 직접 작업하는 것은 까다로울 수 있어, Shay는 Java 프로그래머가 그들의
응용프로그램에 검색을 쉽게 추가할 수 있도록, 추상화 계층에 대한 작업을 시작했다.
그는 Compass라는 그의 첫 번째 open source 프로젝트를 발표했다.

나중에, Shay는 in-memory data grid를 가진 고성능, 분산 환경에서 일하는 직업을 가졌다.
고성능, 실시간, 분산 검색엔진은 분명히 필요했다. 그래서, 그는 Compass를 Elasticsearch라
불리는 독립서버로 다시 만들기로 결정했다.

첫 번째 공개 버전은 2010년 2월에 발표되었다. 그 이후, Elasticsearch는 300여명의
참여자가 commit하는, GitHub에서 가장 인기 있는 프로젝트가 되었다. Elasticsearch의
상업적인 지원과 새로운 기능을 개발하기 위하여 회사가 설립되었지만, Elasticsearch는
open source이고 누구나 이용할 수 있고, 앞으로도 그럴 것이다.

Shay의 아내는 여전히 조리법 검색을 기다리고 있는 중이다...

***************************************





== You Know, for Search...

Elasticsearch is an open-source search engine built on top of
https://lucene.apache.org/core/[Apache Lucene(TM)], a full-text search-engine
library.((("Apache Lucene")))((("Lucene")))  Lucene is arguably the most advanced, high-performance, and fully featured
search engine library in existence today--both open source and proprietary.

But Lucene is just a library. To leverage its power, you need to work in Java
and to integrate Lucene directly with your application. Worse, you will likely
require a degree in information retrieval to understand how it works.  Lucene
is _very_ complex.

Elasticsearch is also written in Java((("Java"))) and uses Lucene internally for all of
its indexing and searching, but it aims to make full-text search easy by hiding
the complexities of Lucene behind a simple, coherent, RESTful API.

However, Elasticsearch is much more than just Lucene and much more than
``just'' full-text search.((("Elasticsearch", "capabilities"))) It can also be described as follows:

* A distributed real-time document store where _every field_ is indexed and
  searchable
* A distributed search engine with real-time analytics
* Capable of scaling to hundreds of servers and petabytes of structured
  and unstructured data

And it packages up all this functionality into a standalone server that
your application can talk to via a simple RESTful API, using a web client from
your favorite programming language, or even from the command line.

It is easy to get started with Elasticsearch. It ships with sensible defaults
and hides complicated search theory away from beginners. It _just works_,
right out of the box. With minimal understanding, you can soon become
productive.((("Elasticsearch", "installing")))

Elasticsearch can be((("Apache 2 license"))) downloaded, used, and modified free of charge. It is
available under the http://www.apache.org/licenses/LICENSE-2.0.html[Apache 2 license],
one of the most flexible open source licenses available.

As your knowledge grows, you can leverage more of Elasticsearch's advanced
features. The entire engine is configurable and flexible. Pick and choose
from the advanced features to tailor Elasticsearch to your problem domain.

.The Mists of Time
***************************************

Many years ago, a newly married unemployed developer called Shay Banon
followed his wife to London, where she was studying to be a chef. While looking
for gainful employment, he started playing with an early version of Lucene,
with the intent of building his wife a recipe search engine.

Working directly with Lucene can be tricky, so Shay started work on an
abstraction layer to make it easier for Java programmers to add search to
their applications.  He released this as his first open source project, called
Compass.

Later Shay took a job working in a high-performance, distributed environment
with in-memory data grids.  The need for a high-performance, real-time,
distributed search engine was obvious, and he decided to rewrite the Compass
libraries as a standalone server called Elasticsearch.

The first public release came out in February 2010.  Since then, Elasticsearch
has become one of the most popular projects on GitHub with commits from over
300 contributors.  A company has formed around Elasticsearch to provide
commercial support and to develop new features, but Elasticsearch is, and
forever will be, open source and available to all.

Shay's wife is still waiting for the recipe search...

***************************************
