=== Elasticsearch의 설치

Elasticsearch로 무엇을 할 수 있는지를 이해하는 가장 쉬운 방법은 동작시켜 보는 것이다.
자, 시작해 보자!((("Elasticsearch", "installing")))

Elasticsearch를 설치하기 위해 필요한 최소 요구 조건은 Java 최신 버전이다. 가급적이면,
http://www.java.com[_www.java.com_]에서 가장 최근 버전의 공식 Java를 설치해야 한다.

Elasticsearch의 최신 버전은 http://www.elasticsearch.org/download/[_elasticsearch.org/download_]
에서 다운 받을 수 있다.

[source,sh]
--------------------------------------------------
curl -L -O http://download.elasticsearch.org/PATH/TO/VERSION.zip <1>
unzip elasticsearch-$VERSION.zip
cd  elasticsearch-$VERSION
--------------------------------------------------
<1> 가장 최근 버전은 URL http://www.elasticsearch.org/download/[_elasticsearch.org/download_]
    에서 이용 가능하다.

[TIP]
====
Elasticsearch를 설치할 때, 위에서 언급한 방법이나 http://www.elasticsearch.org/downloads[downloads page] 에서 제공하는
Debian이나 RPM package를 이용할 수 있다. 공식적으로 지원되는 https://github.com/elasticsearch/puppet-elasticsearch[Puppet module]e 이나
https://github.com/elasticsearch/cookbook-elasticsearch[Chef cookbook] 을 이용할 수도 있다.
====

[[Marvel]]
==== Marvel의 설치
http://www.elasticsearch.com/products/Marvel[Marvel] 은 개발 시에 무료로 사용할 수
있는 Elasticsearch를 위한, 관리(("Marvel", "defined"))) tool이다.
Sense라는((("Sense console (Marvel plugin)"))) 대화형 콘솔이 제공되는데, 이를 이용해
Browser에서 매우 쉽게 Elasticsearch에 접근할 수 있다.

이 책의 많은 예제 code는 “View in Sense” link를 포함하고 있다. 그 link를 클릭하면
예제 code가 Sense 콘솔에서 열릴 것이다. 반드시 Marvel을 설치할 필요는 없다.
하지만 설치를 하면 local Elasticsearch cluster에서 이 예제 code를 테스트함으로써,
이 책을 좀 더 이해할 수 있을 것이다.

Marvel은 plugin으로 이용 가능하다.((("Marvel", "downloading and installing")))
Marvel을 내려 받고 설치하기 위해서, Elasticsearch 디렉토리에서 아래 명령어를 실행하자:

Marvel is available as a plug-in.((("Marvel", "downloading and installing"))) To download and install it, run this command
in the Elasticsearch directory:

[source,sh]
--------------------------------------------------
./bin/plugin -i elasticsearch/Marvel/latest
--------------------------------------------------

Marvel은 인터넷 연결이 안될 경우 여기에서 https://www.elastic.co/guide/en/Marvel/1.3/installation.html[수동 설치] 가능하다.

Marvel이 local cluster를 더 이상 모니터 하지 않도록 하려면, 아래 명령어를 통해 데이터
수집을 비활성화할 수 있다:

[source,sh]
--------------------------------------------------
echo 'Marvel.agent.enabled: false' >> ./config/elasticsearch.yml
--------------------------------------------------

[[running-elasticsearch]]
=== Elasticsearch 실행
이제 Elasticsearch를 실행할 준비가 되었다. ((("Elasticsearch", "running")))
아래 명령어를 통해 foreground로 실행할 수 있다.

[source,sh]
--------------------------------------------------
./bin/elasticsearch
--------------------------------------------------
daemon으로 background에서 실행하려면 `-d` 옵션을 추가한다.
잘 실행되었는지 확인하기 위해, 다른 terminal을 열어 아래 명령어를 입력해 보자:

[source,sh]
--------------------------------------------------
curl 'http://localhost:9200/?pretty'
--------------------------------------------------

다음과 같은 응답을 볼 수 있을 것이다:

[source,js]
--------------------------------------------------
{
   "status": 200,
   "name": "Shrunken Bones",
   "version": {
      "number": "1.4.0",
      "lucene_version": "4.10"
   },
   "tagline": "You Know, for Search"
}
--------------------------------------------------
// SENSE: 010_Intro/10_Info.json

이는 Elasticsearch _cluster_가 올라와 실행이 되고 있고, 그것을 테스트할 수 있다는
것을 의미한다.

NOTE: _node_는 Elasticsearch의 실행 중인 instance이다.((("nodes", "defined")))
_cluster_는((("clusters", "defined"))) 동일한 `cluster.name`을 가진 node의 그룹이고,
데이터를 공유하고 장애 대비, 확장 등을 제공하기 위해 함께 동작한다. 단, 단일 node는
그 자체로 단일 cluster를 구성할 수 있다.

동일한 이름을 가진 동일한 네트워크에 있는 다른 cluster에 포함시키기 위해, 현재의 node를 중단하고((("clusters", "changing default name"))),
기본 `cluster.name`을 적절한 무엇인가로 바꾸어야 한다!

이를 위해 `config/` directory에 있는 `elasticsearch.yml`을 편집하고, Elasticsearch를
다시 시작해야 한다. Elasticsearch가 foreground에서 실행되고 있다면, Ctrl-C를 눌러 중단할 수 있다.
그렇지 않다면, `shutdown` API를 사용해야 한다.

[source,sh]
--------------------------------------------------
curl -XPOST 'http://localhost:9200/_shutdown'
--------------------------------------------------


==== Viewing Marvel and Sense

<<Marvel,Marvel>>((("Marvel", "viewing"))) 관리 툴과 모니터링 툴을 설치했다면,
web browser에서 http://localhost:9200/_plugin/marvel/을 방문하여 그것을 볼 수 있다.

Marvel에서 ``Marvel dashboards''를 click하거나 여기를 빙믄히먄  _Sense_ developer((("Sense console (Marvel plugin)", "viewing")))
console로 이동할 수 있다.
http://localhost:9200/_plugin/Marvel/sense/.





=== Installing Elasticsearch

The easiest way to understand what Elasticsearch can do for you is to
play with it, so let's get started!((("Elasticsearch", "installing")))

The only requirement for installing Elasticsearch is a recent version of Java.
Preferably, you should install the latest version of the((("Java", "installing"))) official Java
from http://www.java.com[_www.java.com_].

You can download the latest version of Elasticsearch from
http://www.elasticsearch.org/download/[_elasticsearch.org/download_].

[source,sh]
--------------------------------------------------
curl -L -O http://download.elasticsearch.org/PATH/TO/VERSION.zip <1>
unzip elasticsearch-$VERSION.zip
cd  elasticsearch-$VERSION
--------------------------------------------------
<1> Fill in the URL for the latest version available on
    http://www.elasticsearch.org/download/[_elasticsearch.org/download_].

[TIP]
====
When installing Elasticsearch in production, you can use the method
described previously, or the Debian or RPM packages provided on the
http://www.elasticsearch.org/downloads[downloads page]. You can also use
the officially supported
https://github.com/elasticsearch/puppet-elasticsearch[Puppet module] or
https://github.com/elasticsearch/cookbook-elasticsearch[Chef cookbook].
====

[[marvel]]
==== Installing Marvel

http://www.elasticsearch.com/products/marvel[Marvel] is a management((("Marvel", "defined"))) and monitoring
tool for Elasticsearch, which is free for development use. It comes with an
interactive console called Sense,((("Sense console (Marvel plugin)"))) which makes it easy to talk to
Elasticsearch directly from your browser.

Many of the code examples in the online version of this book include a View in Sense link. When
clicked, it will open up a working example of the code in the Sense console.
You do not have to install Marvel, but it will make this book much more
interactive by allowing you to  experiment with the code samples on your local
Elasticsearch cluster.

Marvel is available as a plug-in.((("Marvel", "downloading and installing"))) To download and install it, run this command
in the Elasticsearch directory:

[source,sh]
--------------------------------------------------
./bin/plugin -i elasticsearch/marvel/latest
--------------------------------------------------

Marvel can also be installed using a https://www.elastic.co/guide/en/marvel/1.3/installation.html[manual process] if you don't have internet connectivity.

You probably don't want Marvel to monitor your local cluster, so you can
disable data collection with this command:

[source,sh]
--------------------------------------------------
echo 'marvel.agent.enabled: false' >> ./config/elasticsearch.yml
--------------------------------------------------

[[running-elasticsearch]]
=== Running Elasticsearch

Elasticsearch is now ready to run. ((("Elasticsearch", "running")))You can start it up in the foreground
with this:

[source,sh]
--------------------------------------------------
./bin/elasticsearch
--------------------------------------------------
Add `-d` if you want to run it in the background as a daemon.

Test it out by opening another terminal window and running the following:

[source,sh]
--------------------------------------------------
curl 'http://localhost:9200/?pretty'
--------------------------------------------------


You should see a response like this:

[source,js]
--------------------------------------------------
{
   "status": 200,
   "name": "Shrunken Bones",
   "version": {
      "number": "1.4.0",
      "lucene_version": "4.10"
   },
   "tagline": "You Know, for Search"
}
--------------------------------------------------
// SENSE: 010_Intro/10_Info.json

This means that your Elasticsearch _cluster_ is up and running, and we can
start experimenting with it.

NOTE: A _node_ is a running instance of Elasticsearch.((("nodes", "defined"))) A _cluster_ is ((("clusters", "defined")))a group of
nodes with the same `cluster.name` that are working together to share data
and to provide failover and scale, although a single node can form a cluster
all by itself.

You should change the default `cluster.name` to something appropriate to you,
like your own name, to stop ((("clusters", "changing default name")))your nodes from trying to join another cluster on
the same network with the same name!

You can do this by editing the `elasticsearch.yml` file in the `config/`
directory and then restarting Elasticsearch.  When Elasticsearch is running in
the foreground, you can stop it by pressing Ctrl-C; otherwise, you can shut
it down with the `shutdown` API:

[source,sh]
--------------------------------------------------
curl -XPOST 'http://localhost:9200/_shutdown'
--------------------------------------------------


==== Viewing Marvel and Sense

If you installed the <<marvel,Marvel>> management ((("Marvel", "viewing")))and monitoring tool, you can
view it in a web browser by visiting
http://localhost:9200/_plugin/marvel/.

You can reach the _Sense_ developer((("Sense console (Marvel plugin)", "viewing"))) console either by clicking the ``Marvel
dashboards'' drop-down in Marvel, or by visiting
http://localhost:9200/_plugin/marvel/sense/.
